export enum CategoryProps {
    'Arquitetura e Urbanismo',
    'Artes',
    'Ciencia e Tecnologia',
    'Cinema e Video',
    'Design e Moda',
    'Educacao',
    'Esporte',
    'Eventos',
    'Fotografia',
    'Gastronomia',
    'Jogos',
    'Jornalismo',
    'Literatura',
    'Música',
    'Pessoais',
    'Podcast',
    'Quadrinhos',
    'Socio ambiental',
    'Teatro e Danca'
}